name       : nmap
version    : 7.10
release    : 4
source     :
    - https://nmap.org/dist/nmap-7.10.tar.bz2 : 58cf8896d09057d1c3533f430c06b22791d0227ebbb93dede2ccb73693ed4b4b
license    : GPL-2.0
summary    : Utility for network discovery and security auditing
description: |
    Utility for network discovery and security auditing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
