name       : nmap
version    : 6.47
release    : 1
source     :
    - http://nmap.org/dist/nmap-6.47.tar.bz2 : 8fa11e9e203ce2d81a207db5ca4f110a525f6c01c1dd0018325a7112a51aa591
license    : GPL-2.0
clang      : no
summary    : Utility for network discovery and security auditing
description: |
    Utility for network discovery and security auditing
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
