name       : nmap
version    : '7.80'
release    : 14
source     :
    - https://nmap.org/dist/nmap-7.80.tar.bz2 : fcfa5a0e42099e12e4bf7a68ebe6fde05553383a682e816a7ec9256ab4773faa
license    : GPL-2.0-only
component  : network.utils
summary    : Utility for network discovery and security auditing
description: |
    Nmap (Network Mapper) is an utility for network discovery and security auditing. Many systems and network administrators also find it useful for tasks such as network inventory, managing service upgrade schedules, and monitoring host or service uptime. Nmap uses raw IP packets in novel ways to determine what hosts are available on the network, what services (application name and version) those hosts are offering, what operating systems (and OS versions) they are running, what type of packet filters/firewalls are in use, and dozens of other characteristics. It was designed to rapidly scan large networks, but works fine against single hosts. In addition to the classic command-line Nmap executable, the Nmap suite includes an advanced GUI and results viewer (Zenmap), a flexible data transfer, redirection, and debugging tool (Ncat), a utility for comparing scan results (Ndiff), and a packet generation and response analysis tool (Nping).
builddeps  :
    - pkgconfig(libpcre)
    - pkgconfig(libssh2)
rundeps    :
    - python-gtk2
setup      : |
    %patch -p1 < $pkgfiles/0001-zenmap-Use-pkexec-to-gain-root-privileges.patch
    %configure
build      : |
    %make
install    : |
    %make_install
