name       : nmap
version    : '7.31'
release    : 6
source     :
    - https://nmap.org/dist/nmap-7.31.tar.bz2 : cb9f4e03c0771c709cd47dc8fc6ac3421eadbdd313f0aae52276829290583842
license    : GPL-2.0
summary    : Utility for network discovery and security auditing
description: |
    Utility for network discovery and security auditing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
