name       : nmap
version    : 7.12
release    : 5
source     :
    - https://nmap.org/dist/nmap-7.12.tar.bz2 : 63df082a87c95a189865d37304357405160fc6333addcf5b84204c95e0539b04
license    : GPL-2.0
summary    : Utility for network discovery and security auditing
description: |
    Utility for network discovery and security auditing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
