name       : nmap
version    : 7.40
release    : 7
source     :
    - https://nmap.org/dist/nmap-7.40.tar.bz2 : 9e14665fffd054554d129d62c13ad95a7b5c7a046daa2290501909e65f4d3188
license    : GPL-2.0
component  : network.utils
summary    : Utility for network discovery and security auditing
description: |
    Utility for network discovery and security auditing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
