name       : nmap
version    : 7.00
release    : 3
source     :
    - https://nmap.org/dist/nmap-7.00.tar.bz2 : 9f442301c615c608a385831c3505cdfed9b0795cd100f1a258b04509802802ae
license    : GPL-2.0
summary    : Utility for network discovery and security auditing
description: |
    Utility for network discovery and security auditing
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
